#!/usr/bin/env python3
"""Validate the static Shipmates site (site/) with stdlib only.

Runs identically in local self-check and in CI. Asserts the invariants the
published site must hold: every page exists, is self-contained (no external
CSS/JS/font hosts), every local reference resolves on disk and stays inside
site/, has exactly one <h1> and a heading outline that never skips a level,
unique head SEO metadata, valid JSON-LD, and a token-driven CSS.

The per-command detail pages under site/commands/<slug>/ are generated by
tools/gen_command_pages.py from skills/<slug>/SKILL.md. This script is the
independent gate on that output: page coverage is derived from skills/*/SKILL.md
(never a hardcoded count), stage counts must agree across source, markup and
JSON-LD, and every source line must survive verbatim into the rendered page.

The docs section (site/docs/index.html plus one leaf per DOCS_SLUGS) is
hand-maintained: every slug must have a page, the hub is a CollectionPage and
each leaf a TechArticle, and every docs page links back to its parent.

The crew section (site/agents/<role>/index.html) carries one page per
agents/*.md file: a TechArticle with a back-link to the homepage crew grid,
the four required section anchors, a reference card whose values match the
agent's frontmatter, and prose that paraphrases rather than lifts the persona
body verbatim.

Exit 0 = all green; exit 1 = one or more failures (printed)."""

from __future__ import annotations
import json
import atexit
import contextlib
import io
import re
import tempfile
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "site"
INDEX = SITE / "index.html"
CSS = SITE / "styles.css"
SITEMAP = SITE / "sitemap.xml"
# The site is generated from the RENDERED payload, not the neutral source, so
# the independent gate has to read the same thing. Comparing pages against
# `commands/` would flag every rendered token (`$ARGUMENTS` vs `{{issue}}`,
# `.claude/agents/*.md` vs `agent-files/*.md`) as a fidelity failure.
SITE_TARGET = "claude-code"
_PAYLOAD = tempfile.TemporaryDirectory()
atexit.register(_PAYLOAD.cleanup)
import subprocess

res = subprocess.run(
    ["cargo", "run", "--", "build", "--target", SITE_TARGET, "--out", _PAYLOAD.name],
    cwd=ROOT,
    capture_output=True,
    text=True,
)
if res.returncode != 0:
    raise SystemExit(f"error: could not build the {SITE_TARGET} payload to validate against: {res.stderr}")
_RENDERED = Path(_PAYLOAD.name) / "harnesses" / SITE_TARGET / ".claude"
COMMANDS = _RENDERED / "skills"
CREW = _RENDERED / "agents"

SITE_URL = "https://saman-mb.github.io/shipmates/"
SITEMAP_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"
LASTMOD_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
SOURCE_STAGE_RE = re.compile(r"^## Stage ", re.M)
REGEN_HINT = "run: python3 tools/gen_command_pages.py && git add site/"
MAX_DESC = 160
BACK_HREF = "../../#commands"
# The docs hub sits one level below site/ (unlike command pages at two), so
# its homepage back-link is "../" — "../../" would resolve outside site/ and
# trip the local-refs containment check (and escape the /shipmates/ Pages
# sub-path once published).
DOCS_HUB_BACK_HREF = "../"
DOCS_LEAF_BACK_HREF = "../"

# The hand-maintained docs section: one leaf page per slug, hard error if any
# is missing (the hub is checked separately in check_docs_coverage).
DOCS_SLUGS = ("install", "harnesses", "troubleshooting", "architecture")

# One published detail page per agents/*.md — the filename is the role handle.
AGENT_SLUGS = tuple(p.stem for p in sorted(CREW.glob("*.md")))
AGENT_BACK_HREF = "../../#crew"
# Section anchors every agent page must carry.
AGENT_SECTIONS = ("scenarios", "checks", "crew-fit", "reference")

# C3 — every class the generator emits on a detail page (plus the two the
# homepage order cards gained) must have a rule in styles.css.
C3_CLASSES = (
    "order-detail", "section__eyebrow", "order-detail__flag",
    "order-detail__title", "order-detail__tagline", "order-detail__desc",
    "order-back",
    "order-invoke", "order-invoke__hint",
    "order-stages", "order-stage", "order-stage__num",
    "order-stage__title", "order-stage__gate", "order-stage__crew",
    "order-stage__crew-item", "order-stage__body",
    "order-prose", "order-code", "order-table",
    "order-source",
    "demo", "demo__media", "demo__toggle", "demo__caption",
    "order-siblings", "order-siblings__list", "order-siblings__item",
    "order-siblings__link", "order-siblings__link--current",
    "order-card__link", "order-card__more",
    "agent-scenarios", "agent-scenario", "agent-scenario__title",
    "agent-scenario__desc",
    "agent-ref",
    "crew-card__link", "crew-card__more",
)

# Markdown markers that must never survive tokenization into rendered text.
MARKDOWN_LEAKS = ("**", "`", "](")

# Tags whose text content is not page prose.
NON_PROSE_TAGS = frozenset({"script", "style", "svg"})

failures: list[str] = []
notes: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)


def ok(msg: str) -> None:
    notes.append(msg)


class Collector(HTMLParser):
    """Collects refs, headings, classes, prose and the JSON-LD payload."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.refs: list[tuple[str, dict]] = []  # (tag, attrs)
        self.h1 = 0
        self.headings: list[tuple[int, str]] = []  # (level, text)
        self.classes: list[str] = []
        self.ids: list[str] = []
        self.title = ""
        self.text: list[str] = []  # prose text nodes, verbatim
        self.flow: list[str] = []  # prose text nodes + a space per tag boundary
        # One entry per <script type="application/ld+json"> block. A single
        # concatenated string would make two blocks unparseable and hide the
        # C6 "exactly one block" violation instead of reporting it.
        self.ldjson_blocks: list[str] = []
        self._ldjson: list[str] | None = None
        self._heading: tuple[int, list[str]] | None = None
        self._in_title = False
        self._skip = 0

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        a = {k.lower(): (v or "") for k, v in attrs}
        self.refs.append((tag, a))
        self.classes.extend(a.get("class", "").split())
        if a.get("id"):
            self.ids.append(a["id"])
        if tag == "h1":
            self.h1 += 1
        if tag == "title":
            self._in_title = True
        if len(tag) == 2 and tag[0] == "h" and tag[1].isdigit():
            self._heading = (int(tag[1]), [])
        if tag in NON_PROSE_TAGS:
            self._skip += 1
        if tag == "script" and a.get("type", "").lower() == "application/ld+json":
            self._ldjson = []
        self.flow.append(" ")

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag == "script" and self._ldjson is not None:
            self.ldjson_blocks.append("".join(self._ldjson))
            self._ldjson = None
        if tag == "title":
            self._in_title = False
        if self._heading is not None and len(tag) == 2 and tag[0] == "h" and tag[1].isdigit():
            level, parts = self._heading
            self.headings.append((level, "".join(parts).strip()))
            self._heading = None
        if tag in NON_PROSE_TAGS:
            self._skip -= 1
        self.flow.append(" ")

    def handle_data(self, data):
        if self._ldjson is not None:
            self._ldjson.append(data)
            return
        if self._in_title:
            self.title += data
        if self._skip == 0:
            self.text.append(data)
            self.flow.append(data)
            if self._heading is not None:
                self._heading[1].append(data)


@dataclass
class Page:
    path: Path
    rel: str
    html: str
    collector: Collector

    @property
    def url(self) -> str:
        tail = self.path.relative_to(SITE).as_posix()
        return SITE_URL + tail[: -len("index.html")]

    @property
    def slug(self) -> str:
        return self.path.parent.name

    def attr(self, tag: str, key: str, value: str, want: str) -> str | None:
        """First `want` attribute of the first <tag key="value"> element."""
        for t, a in self.collector.refs:
            if t == tag and a.get(key, "").lower() == value:
                return a.get(want, "")
        return None


def is_external(url: str) -> bool:
    return bool(re.match(r"^(https?:)?//", url.strip()))


def is_local_asset(url: str) -> bool:
    u = url.strip()
    if not u or u.startswith(("#", "mailto:", "tel:", "data:", "javascript:")):
        return False
    return not is_external(u)


def source_slugs() -> list[str]:
    return [p.parent.name for p in sorted(COMMANDS.glob("*/SKILL.md"))]


def crew_roles() -> list[str]:
    """Role handles from agents/*.md — only files that actually declare one, so a
    stray note in agents/ can't move the expected crew count."""
    roles = []
    for path in sorted(CREW.glob("*.md")):
        head = path.read_text(encoding="utf-8").split("---")
        if len(head) > 1 and re.search(r"^name:\s*\S", head[1], re.M):
            roles.append(path.stem)
    return roles


def load_page(path: Path) -> Page:
    html = path.read_text(encoding="utf-8")
    c = Collector()
    c.feed(html)
    c.close()
    return Page(path=path, rel=path.relative_to(ROOT).as_posix(), html=html, collector=c)


def discover_pages(site: Path) -> list[Page]:
    """The homepage plus every generated detail page and docs page, in a stable order."""
    paths = [site / "index.html"]
    paths += sorted(p for p in (site / "commands").glob("*/index.html") if p.is_file())
    docs = site / "docs"
    if (docs / "index.html").is_file():
        paths.append(docs / "index.html")
    paths += sorted(p for p in docs.glob("*/index.html") if p.is_file())
    agents = site / "agents"
    paths += sorted(p for p in agents.glob("*/index.html") if p.is_file())
    return [load_page(p) for p in paths]


# --- per-page checks -------------------------------------------------------


def check_page_common(page: Page, expect_ldjson_type: str) -> None:
    c = page.collector

    # --- exactly one h1 ---
    if c.h1 == 1:
        ok(f"{page.rel}: exactly one <h1>")
    else:
        fail(f"{page.rel}: expected exactly one <h1>, found {c.h1}")

    # --- heading outline never skips a level (a11y) ---
    check_heading_outline(page)

    # --- external CSS / JS (self-contained requirement) ---
    external = False
    for tag, a in c.refs:
        if tag == "link" and "stylesheet" in a.get("rel", "").lower() and is_external(a.get("href", "")):
            fail(f"{page.rel}: external stylesheet: {a.get('href')}")
            external = True
        if tag == "script" and is_external(a.get("src", "")):
            fail(f"{page.rel}: external script: {a.get('src')}")
            external = True
    if not external:
        ok(f"{page.rel}: self-contained (no external CSS/JS/font hosts)")

    check_local_refs(page)
    check_ldjson_block(page, expect_ldjson_type)
    check_head_seo(page)


def check_heading_outline(page: Page) -> None:
    headings = page.collector.headings
    if not headings:
        fail(f"{page.rel}: no headings found")
        return
    if headings[0][0] != 1:
        fail(f"{page.rel}: first heading is <h{headings[0][0]}>, expected <h1>")
        return
    prev = 1
    for level, text in headings[1:]:
        if level > prev + 1:
            fail(
                f"{page.rel}: heading outline skips a level — <h{prev}> "
                f"followed by <h{level}> ({text[:60]!r})"
            )
            return
        prev = level
    ok(f"{page.rel}: heading outline h1..h{max(l for l, _ in headings)} never skips a level")


def check_local_refs(page: Page) -> None:
    """Every local src/href resolves on disk and stays inside site/.

    Resolved against the PAGE's directory, not site/ — a detail page reaches
    the site root via ../../ and its siblings via ../<slug>/. Containment is
    Path.is_relative_to on resolved paths, never a string prefix (a sibling
    `site-old/` string-prefixes `site`), so a symlink out of the tree is
    caught too — the Pages artifact would follow it.
    """
    site_res = SITE.resolve()
    problems: list[str] = []
    checked = 0
    for _tag, a in page.collector.refs:
        for attr in ("src", "href"):
            url = a.get(attr, "")
            if not is_local_asset(url):
                continue
            raw = url.split("?")[0].split("#")[0]
            if raw == "":
                continue  # pure fragment or query against this same page
            checked += 1
            if raw.startswith("/"):
                problems.append(f"'{url}' is an absolute path — escapes the /shipmates/ Pages sub-path")
                continue
            target = (page.path.parent / raw).resolve()
            if not (target == site_res or target.is_relative_to(site_res)):
                problems.append(f"'{url}' resolves outside site/ -> {target}")
                continue
            if raw.endswith("/") or target.is_dir():
                if not (target / "index.html").is_file():
                    problems.append(f"'{url}' has no index.html")
            elif not target.is_file():
                problems.append(f"referenced local asset not found: {url}")
    for p in sorted(set(problems)):
        fail(f"{page.rel}: {p}")
    if not problems:
        ok(f"{page.rel}: all {checked} local reference(s) resolve inside site/")


def check_ldjson_block(page: Page, expect_type: str) -> dict | None:
    blocks = page.collector.ldjson_blocks
    if not blocks or not blocks[0].strip():
        fail(f"{page.rel}: no JSON-LD <script type=application/ld+json> block found")
        return None
    if len(blocks) > 1:
        fail(
            f"{page.rel}: found {len(blocks)} JSON-LD blocks, expected exactly 1 "
            "(consumers merge sibling blocks unreliably; emit one graph)"
        )
        return None
    try:
        data = json.loads(blocks[0])
    except json.JSONDecodeError as e:
        fail(f"{page.rel}: JSON-LD does not parse: {e}")
        return None
    if not isinstance(data, dict):
        fail(f"{page.rel}: JSON-LD top level is {type(data).__name__}, expected an object")
        return None
    if data.get("@type") != expect_type:
        fail(f"{page.rel}: JSON-LD @type is {data.get('@type')!r}, expected {expect_type}")
        return None
    ok(f"{page.rel}: JSON-LD parses ({expect_type})")
    return data


def check_head_seo(page: Page) -> None:
    missing = []
    if not re.search(r"<title>[^<]+</title>", page.html):
        missing.append("missing non-empty <title>")
    if 'name="description"' not in page.html:
        missing.append("missing meta description")
    if 'rel="canonical"' not in page.html:
        missing.append("missing canonical link")
    if 'property="og:image"' not in page.html:
        missing.append("missing og:image")
    if 'lang="en"' not in page.html:
        missing.append("missing <html lang=\"en\">")
    for m in missing:
        fail(f"{page.rel}: {m}")
    if not missing:
        ok(f"{page.rel}: head SEO tags present (title, description, canonical, og:image)")

    # canonical and og:url must name the same URL, or crawlers pick one at random
    canonical = page.attr("link", "rel", "canonical", "href")
    og_url = page.attr("meta", "property", "og:url", "content")
    if canonical is None or og_url is None:
        if canonical is not None:
            fail(f"{page.rel}: has a canonical but no og:url")
        return
    if canonical != og_url:
        fail(f"{page.rel}: canonical {canonical!r} != og:url {og_url!r}")
    elif canonical != page.url:
        fail(f"{page.rel}: canonical {canonical!r} does not match its own URL {page.url!r}")
    else:
        ok(f"{page.rel}: canonical == og:url == {canonical}")


def check_homepage(page: Page, css: str, n_commands: int) -> None:
    # --- no '../' escaping the published root (blunt; homepage only) ---
    if "../" in page.html:
        fail(f"{page.rel}: contains '../' path(s) — would escape the Pages root")
    else:
        ok(f"{page.rel}: no '../' path traversal")

    # --- component counts (acceptance criteria) ---
    counts = {
        "crew-card": (len(re.findall(r'class="crew-card(?:\s|")', page.html)), len(crew_roles())),
        "order-card": (len(re.findall(r'class="order-card(?:\s|")', page.html)), n_commands),
        "order-card--flagship": (page.html.count("order-card--flagship"), 1),
        "how-step": (len(re.findall(r'class="how-step"', page.html)), 8),
        "faq__item": (len(re.findall(r'class="faq__item"', page.html)), 7),
    }
    for name, (got, want) in counts.items():
        if got == want:
            ok(f"{page.rel}: {name}: {got}")
        elif name == "order-card":
            fail(
                f"{page.rel}: order-card: expected {want} (one per skills/*/SKILL.md), found {got} — "
                f"add or remove the card, then {REGEN_HINT}"
            )
        else:
            fail(f"{page.rel}: {name}: expected {want}, found {got}")

    # --- every card actually links to its detail page ---
    # Counted from the parsed class list so an extra class on the element
    # (e.g. class="btn order-card__link") cannot silently pass.
    n_cards = counts["order-card"][0]
    n_links = page.collector.classes.count("order-card__link")
    if n_links == n_cards == n_commands:
        ok(f"{page.rel}: order-card__link: {n_links} (one per card)")
    else:
        fail(
            f"{page.rel}: order-card__link: found {n_links}, expected one per order-card "
            f"({n_cards}) and one per skills/*/SKILL.md ({n_commands}) — a card with no link "
            "strands its detail page"
        )

    # --- every crew card links to its agent page (same tripwire as the order cards) ---
    n_crew = counts["crew-card"][0]
    n_crew_links = page.collector.classes.count("crew-card__link")
    if n_crew_links == n_crew == len(crew_roles()):
        ok(f"{page.rel}: crew-card__link: {n_crew_links} (one per card)")
    else:
        fail(
            f"{page.rel}: crew-card__link: found {n_crew_links}, expected one per crew-card "
            f"({n_crew}) and one per agents/*.md ({len(crew_roles())}) — a card with no link "
            "strands its agent page"
        )

    # --- crew cards name real roles, not merely the right number of them ---
    shown = set(re.findall(r'class="crew-card__handle">([^<]+)</code>', page.html))
    roles = set(crew_roles())
    if shown and shown != roles:
        for h in sorted(shown - roles):
            fail(f"{page.rel}: crew-card '{h}' has no agents/{h}.md")
        for h in sorted(roles - shown):
            fail(f"{page.rel}: agents/{h}.md has no crew-card")
    elif shown:
        ok(f"{page.rel}: all {len(shown)} crew-card handles resolve to agents/*.md")

    # --- prose counts track the same source as the cards ---
    # Deriving the card count removed the hardcoded constant that used to force a human
    # to notice the other places the number lives; this is the replacement tripwire.
    chip = re.search(r'class="chip">(\d+)\s+specialists</li>', page.html)
    if chip and int(chip.group(1)) != len(roles):
        fail(
            f"{page.rel}: hero chip says {chip.group(1)} specialists but agents/*.md has "
            f"{len(roles)} — the prose counts in README.md, AGENTS.md and docs/BRAND.md "
            "likely need the same bump"
        )
    elif chip:
        ok(f"{page.rel}: hero chip matches agents/*.md ({chip.group(1)} specialists)")

    # --- homepage links into the docs section (install section + FAQ entry) ---
    n_docs_links = sum(
        1
        for _t, a in page.collector.refs
        if is_local_asset(a.get("href", "")) and a["href"].startswith("docs/")
    )
    if n_docs_links >= 2:
        ok(f"{page.rel}: {n_docs_links} link(s) into docs/")
    else:
        fail(
            f"{page.rel}: {n_docs_links} link(s) into docs/, expected at least 2 "
            "(the install section link and the docs FAQ entry)"
        )

    # --- reduced-motion demo poster wired (a11y / WCAG 2.2.2) ---
    # Three valid approaches:
    #   1. <picture> with <source media="(prefers-reduced-motion: reduce)">
    #   2. CSS swap with .hero__demo-poster <img> + prefers-reduced-motion in styles
    #   3. Poster paints by default; a real button starts/stops the motion —
    #      the only one of the three that is itself a WCAG 2.2.2 mechanism (the
    #      other two are OS-level mitigations, not a control in the content)
    has_picture_motion = (
        '<source media="(prefers-reduced-motion: reduce)"' in page.html
    )
    has_css_swap = (
        "hero__demo-poster" in page.html
        and "hero__demo-poster" in css
        and "prefers-reduced-motion" in css
    )
    has_toggle_control = (
        "hero__demo-toggle" in page.html
        and 'aria-pressed="false"' in page.html
        and "demo-poster.png" in page.html
    )
    if has_picture_motion or has_css_swap or has_toggle_control:
        ok(f"{page.rel}: reduced-motion demo poster wired")
    else:
        fail(
            f"{page.rel}: reduced-motion demo poster not wired (need a <picture> with "
            "<source media=\"(prefers-reduced-motion: reduce)\">, a CSS swap, or a "
            "real play/pause control)"
        )


def _src_label(src: Path) -> str:
    """Report a source path relative to the repo when it is inside it.

    Sources are read from a rendered payload in a temp dir, so relative_to(ROOT)
    raises ValueError there — turning a clean failure report into a crash on the
    exact path that only runs when something is already wrong.
    """
    try:
        return src.relative_to(ROOT).as_posix()
    except ValueError:
        return f"{SITE_TARGET}:{src.name}" if src.name != "SKILL.md" else f"{SITE_TARGET}:{src.parent.name}/SKILL.md"


def check_command_page(page: Page) -> None:
    slug = page.slug
    src = COMMANDS / slug / "SKILL.md"

    # --- back-navigation to the commands list on the homepage ---
    if any(a.get("href") == BACK_HREF for _t, a in page.collector.refs):
        ok(f"{page.rel}: back link to {BACK_HREF}")
    else:
        fail(f"{page.rel}: no back-navigation link (expected an href of {BACK_HREF!r})")

    # --- no markdown survived tokenization into rendered text ---
    leaks = sorted({
        marker
        for node in page.collector.text
        for marker in MARKDOWN_LEAKS
        if marker in node
    })
    if leaks:
        sample = next(
            n.strip() for n in page.collector.text if any(m in n for m in leaks)
        )
        fail(
            f"{page.rel}: raw markdown {leaks} leaked into rendered text — {sample[:80]!r} "
            "(the renderer passed a construct through instead of tokenizing it)"
        )
    else:
        ok(f"{page.rel}: no raw markdown in rendered text")

    data = check_ldjson_howto(page)
    check_stage_parity(page, src, data)

    if not src.is_file():
        return  # coverage check already reported the orphan
    check_fidelity(page, src)


def check_ldjson_howto(page: Page) -> dict | None:
    """HowTo.step is a 1..N ordered list of anchors that exist on the page."""
    blocks = page.collector.ldjson_blocks
    if len(blocks) != 1:
        return None  # check_page_common already failed on this
    try:
        data = json.loads(blocks[0])
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None

    for key in ("name", "description", "url"):
        value = data.get(key)
        if not isinstance(value, str) or not value.strip():
            fail(f"{page.rel}: JSON-LD HowTo.{key} is empty or not a string ({value!r})")
    if data.get("url") != page.url:
        fail(f"{page.rel}: JSON-LD HowTo.url is {data.get('url')!r}, expected {page.url!r}")

    steps = data.get("step")
    if not isinstance(steps, list) or not steps:
        fail(f"{page.rel}: JSON-LD HowTo.step must be a non-empty list, got {type(steps).__name__}")
        return data

    ids = set(page.collector.ids)
    bad = 0
    for i, step in enumerate(steps, start=1):
        where = f"{page.rel}: JSON-LD step[{i}]"
        if not isinstance(step, dict):
            fail(f"{where} is {type(step).__name__}, expected an object")
            bad += 1
            continue
        if step.get("@type") != "HowToStep":
            fail(f"{where} @type is {step.get('@type')!r}, expected HowToStep")
            bad += 1
        if step.get("position") != i:
            fail(f"{where} position is {step.get('position')!r}, expected {i} (1..N in order)")
            bad += 1
        for key in ("name", "text"):
            value = step.get(key)
            if not isinstance(value, str) or not value.strip():
                fail(f"{where} {key} is empty or not a string ({value!r})")
                bad += 1
        url = step.get("url")
        if not isinstance(url, str) or not url.startswith(page.url + "#"):
            fail(f"{where} url is {url!r}, expected {page.url!r} + a '#stage-…' fragment")
            bad += 1
        elif url.split("#", 1)[1] not in ids:
            fail(f"{where} url anchor '#{url.split('#', 1)[1]}' has no matching id on the page")
            bad += 1
    if not bad:
        ok(f"{page.rel}: JSON-LD HowTo.step: {len(steps)} steps, positions 1..{len(steps)}, anchors resolve")
    return data


def check_docs_hub_page(page: Page) -> None:
    """The docs index: links back to the homepage, CollectionPage payload."""
    check_docs_back_link(page, DOCS_HUB_BACK_HREF)
    check_ldjson_docs(page, "CollectionPage")


def check_docs_leaf_page(page: Page) -> None:
    """A docs leaf: links back to the docs index, TechArticle payload."""
    check_docs_back_link(page, DOCS_LEAF_BACK_HREF)
    check_ldjson_docs(page, "TechArticle")


def check_docs_back_link(page: Page, href: str) -> None:
    if any(a.get("href") == href for _t, a in page.collector.refs):
        ok(f"{page.rel}: back link to {href}")
    else:
        fail(f"{page.rel}: no back-navigation link (expected an href of {href!r})")


def check_ldjson_docs(page: Page, ld_type: str) -> None:
    """name/description non-empty, url equal to the page's canonical URL."""
    blocks = page.collector.ldjson_blocks
    if len(blocks) != 1:
        return  # check_page_common already failed on this
    try:
        data = json.loads(blocks[0])
    except json.JSONDecodeError:
        return  # check_page_common already failed on this
    if not isinstance(data, dict):
        return  # check_page_common already failed on this

    for key in ("name", "description"):
        value = data.get(key)
        if not isinstance(value, str) or not value.strip():
            fail(f"{page.rel}: JSON-LD {ld_type}.{key} is empty or not a string ({value!r})")
    if data.get("url") != page.url:
        fail(f"{page.rel}: JSON-LD {ld_type}.url is {data.get('url')!r}, expected {page.url!r}")


def check_stage_parity(page: Page, src: Path, data: dict | None) -> None:
    """Source stage count == rendered stage count == JSON-LD step count."""
    n_markup = page.collector.classes.count("order-stage")
    n_steps = len(data.get("step", [])) if isinstance(data, dict) and isinstance(data.get("step"), list) else None
    if not src.is_file():
        return  # coverage check reports the missing source
    n_source = len(SOURCE_STAGE_RE.findall(src.read_text(encoding="utf-8")))

    if n_steps is None:
        fail(f"{page.rel}: cannot check stage parity — no usable JSON-LD step list")
        return
    if n_source == n_markup == n_steps:
        ok(f"{page.rel}: stage parity: {n_source} in source, markup and JSON-LD")
    else:
        fail(
            f"{page.rel}: stage count mismatch — skills/{page.slug}/SKILL.md has {n_source} "
            f"'## Stage ' heading(s), the page renders {n_markup} .order-stage, the JSON-LD "
            f"lists {n_steps} step(s) — {REGEN_HINT}"
        )


# --- honesty (C8): every source line survives into the rendered page --------

_STAGE_HEADING = re.compile(r"^##\s+Stage\s+\S+\s+.\s+(?P<rest>.+)$")
_TRAILING_PAREN = re.compile(r"\s*\([^()]*\)\s*$")
_DELIMITER_ROW = re.compile(r"[-:| ]+")


def _tokens(s: str) -> str:
    return " ".join(re.sub(r"[*`#>]", " ", s).split())


_ANNOTATION_PREFIX = re.compile(r"^agents?:\s*")
_ANNOTATION_CONNECTOR = r",\s*(?:or|and)\s*"


def _crew_annotation_needles(paren: str, agents: list[str]) -> list[str]:
    """Independent re-derivation of the chip/annotation split tools/gen_command_pages.py
    renders (#136): a name that moved into its own chip no longer needs the whole
    parenthetical repeated verbatim — only the codespan itself (still required,
    now via the chip) and whatever qualifier survives stripping the names and the
    agent:/agents: scaffolding. An annotation with no recognised name (MODE=pr
    notes, "specialist agents") is untouched — the renderer keeps it verbatim too.
    """
    names = [name for name in agents if f"`{name}`" in paren]
    if not names:
        return [paren]
    inner = paren.strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]
    inner = _ANNOTATION_PREFIX.sub("", inner)
    for name in names:
        inner = re.sub(
            rf"(?:{_ANNOTATION_CONNECTOR})?`{re.escape(name)}`(?:{_ANNOTATION_CONNECTOR})?",
            " ",
            inner,
        )
    residue = re.sub(r"\s+", " ", inner).strip(" ,")
    out = [f"`{name}`" for name in names]
    if residue:
        out.append(f"({residue})")
    return out


def _needles(raw: str, in_fence: bool, agents: list[str]) -> list[str]:
    """The plain-text fragments one source line must contribute to the page.

    A stage heading is checked piecewise, not contiguously, because the
    renderer deliberately relocates two of its parts: the ⛔ gate text moves
    into .order-stage__gate and the trailing crew parenthetical into
    .order-stage__crew — itself split further into chips plus qualifier, see
    _crew_annotation_needles.
    """
    if in_fence:
        return [raw]
    stage = _STAGE_HEADING.match(raw.strip())
    if stage is not None:
        rest = stage.group("rest")
        out: list[str] = []
        hit = _TRAILING_PAREN.search(rest)
        if hit:
            out.extend(_crew_annotation_needles(hit.group(0), agents))
            rest = rest[: hit.start()]
        head, mark, gate = rest.partition("⛔")
        if mark:
            hit = _TRAILING_PAREN.search(gate)
            if hit:
                out.extend(_crew_annotation_needles(hit.group(0), agents))
                gate = gate[: hit.start()]
            out.append(gate)
        out.append(head)
        return out
    stripped = re.sub(r"^(\s*)([-*]|\d+\.)\s+", "", raw)
    return [re.sub(r"^#+\s+", "", stripped).replace("|", " ")]


def check_fidelity(page: Page, src: Path) -> None:
    """C8: no sentence on the page that is not in skills/<slug>/SKILL.md, and no
    line of skills/<slug>/SKILL.md that is missing from the page."""
    prose = " " + _tokens("".join(page.collector.flow)) + " "
    agents = crew_roles()
    lines = src.read_text(encoding="utf-8").split("\n")
    try:
        start = lines.index("---", 1) + 1
    except ValueError:
        fail(f"{_src_label(src)}: no closing frontmatter '---' — cannot audit fidelity")
        return

    missing: list[str] = []
    in_fence = False
    for offset, raw in enumerate(lines[start:]):
        lineno = start + offset + 1
        s = raw.strip()
        if s.startswith("```"):
            in_fence = not in_fence
            continue
        if not s or s == "---":
            continue
        if not in_fence and _DELIMITER_ROW.fullmatch(s):
            continue  # GFM table delimiter row is syntax, not prose
        for needle in (_tokens(n) for n in _needles(raw, in_fence, agents)):
            if needle and f" {needle} " not in prose:
                missing.append(f"skills/{page.slug}/SKILL.md:{lineno}: {needle[:70]!r}")

    if missing:
        for line in missing[:5]:
            fail(f"{page.rel}: source text missing from the page — {line}")
        if len(missing) > 5:
            fail(f"{page.rel}: … and {len(missing) - 5} more line(s) missing — {REGEN_HINT}")
    else:
        ok(f"{page.rel}: every line of skills/{page.slug}/SKILL.md appears verbatim in the page")


# --- agent detail pages ----------------------------------------------------

_PUNCT_SPACE = re.compile(r"\s+([,.;:!?])")


def _prose_norm(s: str) -> str:
    """_tokens plus punctuation tightening, so a value split across inline tags
    ("Read</code>, <code>Grep") still matches its single-string source."""
    return _PUNCT_SPACE.sub(r"\1", _tokens(s))


def agent_frontmatter(src: Path) -> dict[str, str]:
    """The flat key: value pairs of an agents/*.md frontmatter block."""
    lines = src.read_text(encoding="utf-8").split("\n")
    try:
        end = lines.index("---", 1)
    except ValueError:
        return {}
    out: dict[str, str] = {}
    for line in lines[1:end]:
        key, sep, value = line.partition(":")
        if sep:
            out[key.strip()] = value.strip()
    return out


def check_agent_page(page: Page) -> None:
    role = page.slug
    src = CREW / f"{role}.md"

    # --- back-navigation to the crew grid on the homepage ---
    if any(a.get("href") == AGENT_BACK_HREF for _t, a in page.collector.refs):
        ok(f"{page.rel}: back link to {AGENT_BACK_HREF}")
    else:
        fail(f"{page.rel}: no back-navigation link (expected an href of {AGENT_BACK_HREF!r})")

    # --- required section anchors ---
    ids = set(page.collector.ids)
    absent = [s for s in AGENT_SECTIONS if s not in ids]
    if absent:
        fail(f"{page.rel}: missing section id(s): {', '.join('#' + s for s in absent)}")
    else:
        ok(f"{page.rel}: all {len(AGENT_SECTIONS)} required section ids present")

    if not src.is_file():
        return  # coverage check already reported the orphan
    check_agent_reference(page, src)
    check_agent_inverse_fidelity(page, src)


def check_agent_reference(page: Page, src: Path) -> None:
    """The reference card restates the persona frontmatter: name, description."""
    front = agent_frontmatter(src)
    if not front:
        fail(f"{_src_label(src)}: no closing frontmatter '---' — cannot audit the reference card")
        return
    prose = " " + _prose_norm("".join(page.collector.flow)) + " "
    missing = []
    for key in ("name", "description"):
        value = front.get(key, "")
        if not value:
            missing.append(f"crew/{page.slug}.md: frontmatter has no '{key}:'")
            continue
        if f" {_prose_norm(value)} " not in prose:
            missing.append(f"frontmatter '{key}' value not found in the page — {value[:70]!r}")
    if missing:
        for m in missing:
            fail(f"{page.rel}: reference card mismatch — {m}")
    else:
        ok(f"{page.rel}: reference card matches crew/{page.slug}.md frontmatter (name, description)")


def check_agent_inverse_fidelity(page: Page, src: Path) -> None:
    """The inverse of the command-page fidelity rule: an agent page paraphrases
    its persona, so no body line of agents/<role>.md may survive verbatim into
    the page prose (frontmatter is exempt — the reference card restates it)."""
    prose = " " + _prose_norm("".join(page.collector.flow)) + " "
    lines = src.read_text(encoding="utf-8").split("\n")
    try:
        start = lines.index("---", 1) + 1
    except ValueError:
        return  # check_agent_reference already failed on this

    leaked: list[str] = []
    in_fence = False
    for offset, raw in enumerate(lines[start:]):
        lineno = start + offset + 1
        s = raw.strip()
        if s.startswith("```"):
            in_fence = not in_fence
            continue
        if not s or in_fence:
            continue
        needle = _prose_norm(re.sub(r"^([-*]|\d+\.)\s+", "", s))
        if len(needle) < 20:
            continue  # too short to prove a lift rather than a coincidence
        if f" {needle} " in prose:
            leaked.append(f"agents/{page.slug}.md:{lineno}: {needle[:70]!r}")

    if leaked:
        for line in leaked[:5]:
            fail(f"{page.rel}: persona body line appears verbatim in the page — {line}")
        if len(leaked) > 5:
            fail(f"{page.rel}: … and {len(leaked) - 5} more lifted line(s)")
    else:
        ok(f"{page.rel}: no body line of agents/{page.slug}.md appears verbatim in the page")


# --- whole-site checks -----------------------------------------------------


def check_coverage(pages: list[Page], slugs: list[str]) -> None:
    """One published page per skills/*/SKILL.md, and no page without a source."""
    published = {p.slug: p for p in pages if p.path.parent.parent.name == "commands"}
    for slug in slugs:
        if slug not in published:
            fail(
                f"no published page for skills/{slug}/SKILL.md — expected "
                f"site/commands/{slug}/index.html; {REGEN_HINT}"
            )
    for slug in sorted(published):
        if slug not in slugs:
            fail(
                f"site/commands/{slug}/index.html has no source skills/{slug}/SKILL.md "
                "(renamed or removed a command? delete the stale page and "
                f"{REGEN_HINT})"
            )
    if len(published) == len(slugs) and all(s in published for s in slugs):
        ok(f"page coverage: {len(slugs)} command(s) in skills/, {len(published)} published")


def check_agent_coverage(pages: list[Page]) -> None:
    """One published page per agents/*.md, and no agent page without a source."""
    published = {p.slug: p for p in pages if p.path.parent.parent.name == "agents"}
    for slug in AGENT_SLUGS:
        if slug not in published:
            fail(
                f"no published page for agents/{slug}.md — expected "
                f"site/agents/{slug}/index.html"
            )
    for slug in sorted(published):
        if slug not in AGENT_SLUGS:
            fail(
                f"site/agents/{slug}/index.html has no source agents/{slug}.md "
                "(renamed or removed a crew role? delete the stale page)"
            )
    if len(published) == len(AGENT_SLUGS) and all(s in published for s in AGENT_SLUGS):
        ok(f"agent coverage: {len(AGENT_SLUGS)} role(s) in agents/, {len(published)} published")


def check_docs_coverage(pages: list[Page]) -> None:
    """The docs hub plus one published leaf per DOCS_SLUGS — hard error if missing."""
    if not (SITE / "docs" / "index.html").is_file():
        fail("missing site/docs/index.html — the docs hub page")
    published = {p.slug for p in pages if p.path.parent.parent.name == "docs"}
    for slug in DOCS_SLUGS:
        if slug not in published:
            fail(f"no published docs page for '{slug}' — expected site/docs/{slug}/index.html")
    if all(s in published for s in DOCS_SLUGS):
        ok(f"docs coverage: hub plus {len(DOCS_SLUGS)} docs page(s) published")


def check_uniqueness(pages: list[Page]) -> None:
    """Duplicate titles or descriptions make pages compete in search results."""
    titles: dict[str, list[str]] = {}
    descs: dict[str, list[str]] = {}
    for page in pages:
        title = page.collector.title.strip()
        if not title:
            continue  # check_head_seo already failed
        titles.setdefault(title, []).append(page.rel)
        desc = page.attr("meta", "name", "description", "content")
        if desc is None:
            continue  # check_head_seo already failed
        desc = desc.strip()
        if not desc:
            fail(f"{page.rel}: meta description is empty")
            continue
        if len(desc) > MAX_DESC:
            fail(f"{page.rel}: meta description is {len(desc)} chars, max {MAX_DESC} — {desc[:60]!r}…")
        descs.setdefault(desc, []).append(page.rel)

    dupes = False
    for title, where in sorted(titles.items()):
        if len(where) > 1:
            fail(f"duplicate <title> {title!r} on {', '.join(where)}")
            dupes = True
    for desc, where in sorted(descs.items()):
        if len(where) > 1:
            fail(f"duplicate meta description {desc[:60]!r}… on {', '.join(where)}")
            dupes = True
    if not dupes:
        ok(f"{len(titles)} unique <title>(s) and {len(descs)} unique meta description(s)")


def check_css(css: str) -> None:
    if "@import" in css:
        fail("styles.css uses @import")
    if re.search(r"url\(\s*['\"]?https?:", css):
        fail("styles.css references an external url(http...)")
    if ":root" not in css:
        fail("styles.css has no :root token block")
    else:
        ok(":root token block present")
    if "prefers-color-scheme: dark" not in css:
        fail("styles.css has no dark-theme override")
    else:
        ok("dark-theme override present")

    unstyled = [c for c in C3_CLASSES if not re.search(r"\." + re.escape(c) + r"(?![\w-])", css)]
    if unstyled:
        fail(f"styles.css has no rule for {len(unstyled)} emitted class(es): {', '.join(unstyled)}")
    else:
        ok(f"all {len(C3_CLASSES)} detail-page class(es) styled")


def check_sitemap(pages: list[Page], n_commands: int, n_docs: int, n_agents: int) -> None:
    if not SITEMAP.is_file():
        fail(f"missing {SITEMAP.relative_to(ROOT).as_posix()}")
        return
    try:
        root = ET.fromstring(SITEMAP.read_text(encoding="utf-8"))
    except ET.ParseError as e:
        fail(f"sitemap.xml does not parse: {e}")
        return

    before = len(failures)
    entries: list[tuple[str, str | None]] = []
    for i, url in enumerate(root.findall(f"{SITEMAP_NS}url"), start=1):
        loc = url.findtext(f"{SITEMAP_NS}loc")
        if loc is None or not loc.strip():
            fail(f"sitemap.xml: <url> #{i} has no <loc>")
            continue
        entries.append((loc.strip(), url.findtext(f"{SITEMAP_NS}lastmod")))

    locs = [loc for loc, _ in entries]
    for loc in sorted({loc for loc in locs if locs.count(loc) > 1}):
        fail(f"sitemap.xml: duplicate <loc> {loc}")

    expected = {p.url for p in pages}
    for url in sorted(expected - set(locs)):
        fail(f"sitemap.xml: no <loc> for {url} — {REGEN_HINT}")
    for url in sorted(set(locs) - expected):
        fail(f"sitemap.xml: <loc> {url} has no page on disk — {REGEN_HINT}")

    for loc, lastmod in entries:
        if lastmod is None or not LASTMOD_RE.match(lastmod.strip()):
            fail(f"sitemap.xml: {loc} has no valid <lastmod> (YYYY-MM-DD), got {lastmod!r}")

    want = 1 + n_commands + n_docs + n_agents
    if len(entries) != want:
        fail(
            f"sitemap.xml: {len(entries)} <url> entries, expected {want} "
            "(homepage + one per command + docs hub and leaves + one per agent)"
        )
    if len(failures) == before:
        ok(f"sitemap.xml: {len(entries)} URLs, all resolve to a page and carry a lastmod")


def main() -> int:
    # --- existence ---
    if not INDEX.is_file():
        fail(f"missing {INDEX.relative_to(ROOT).as_posix()}")
        return report()
    if not CSS.is_file():
        fail(f"missing {CSS.relative_to(ROOT).as_posix()}")
    css = CSS.read_text(encoding="utf-8") if CSS.is_file() else ""

    slugs = source_slugs()
    if not slugs:
        fail("no commands/*.md found — nothing to publish")
        return report()
    n_commands = len(slugs)

    pages = discover_pages(SITE)
    homepage = pages[0]
    command_pages = [p for p in pages if p.path.parent.parent.name == "commands"]
    docs_hub = [p for p in pages if p.path.parent.name == "docs"]
    docs_leaves = [p for p in pages if p.path.parent.parent.name == "docs"]
    n_docs = len(docs_hub) + len(docs_leaves)
    agent_pages = [p for p in pages if p.path.parent.parent.name == "agents"]
    n_agents = len(AGENT_SLUGS)

    check_page_common(homepage, expect_ldjson_type="SoftwareApplication")
    check_homepage(homepage, css, n_commands)

    for page in command_pages:
        check_page_common(page, expect_ldjson_type="HowTo")
        check_command_page(page)

    for page in docs_hub:
        check_page_common(page, expect_ldjson_type="CollectionPage")
        check_docs_hub_page(page)

    for page in docs_leaves:
        check_page_common(page, expect_ldjson_type="TechArticle")
        check_docs_leaf_page(page)

    for page in agent_pages:
        check_page_common(page, expect_ldjson_type="TechArticle")
        check_agent_page(page)

    check_coverage(pages, slugs)
    check_docs_coverage(pages)
    check_agent_coverage(pages)
    check_uniqueness(pages)
    check_css(css)
    check_sitemap(pages, n_commands, n_docs, n_agents)

    return report()


def report() -> int:
    for n in notes:
        print(f"  ok   {n}")
    if failures:
        print()
        for f in failures:
            print(f"  FAIL {f}")
        print(f"\n{len(failures)} failure(s).")
        return 1
    print(f"\nAll {len(notes)} checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
